// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./interfaces/IGroth16Verifier.sol";

/**
 * @title MockGroth16Verifier
 * @notice Mock implementation of Groth16 verifier for testing
 * @dev In production, replace with actual verifier generated by circom/snarkjs
 */
contract MockGroth16Verifier is IGroth16Verifier {
    // For testing: allow setting expected verification result
    bool public alwaysVerify;
    
    // Mapping to store specific proof results for testing
    mapping(bytes32 => bool) public proofResults;
    
    event ProofVerified(bool result);
    
    constructor(bool _alwaysVerify) {
        alwaysVerify = _alwaysVerify;
    }
    
    /**
     * @notice Set whether to always return true for testing
     * @param _alwaysVerify If true, always return true
     */
    function setAlwaysVerify(bool _alwaysVerify) external {
        alwaysVerify = _alwaysVerify;
    }
    
    /**
     * @notice Set a specific proof result for testing
     * @param proofHash Hash of the proof components
     * @param result The result to return for this proof
     */
    function setProofResult(bytes32 proofHash, bool result) external {
        proofResults[proofHash] = result;
    }
    
    /**
     * @notice Verify a Groth16 proof (mock implementation)
     * @dev In production, this would contain actual pairing checks
     */
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[] calldata _pubSignals
    ) external view override returns (bool) {
        // Create a hash of the proof for specific result lookup
        bytes32 proofHash = keccak256(abi.encodePacked(_pA, _pB, _pC, _pubSignals));
        
        // If a specific result is set, return it
        if (proofResults[proofHash]) {
            return true;
        }
        
        // Otherwise return the default behavior
        return alwaysVerify;
    }
}
